default:
	gcc -Ofast bbc.c -o ../bin/bbc -lm -lpthread
	x86_64-w64-mingw32-gcc -Ofast bbc.c -o ../bin/bbc.exe -lm -lpthread

debug:
	gcc -g bbc.c -o ../bin/bbc -lm -lpthread
	x86_64-w64-mingw32-gcc -g bbc.c -o ../bin/bbc.exe -lm -lpthread